### ISSUE TITLE
Task List

### ISSUE THREAD

**Issue by rossmounce** [rossmounce/NHM-specimens#1]
This an issue in which we can assign & list tasks that need to be completed.
Assignment indicated by initials, RM = @rossmounce , AR = @AimeRankin
We can tick each one as and when it is complete. Assignments very much up for negotiation, nothing is fixed.
- [x] PLOS ONE & PMC OA Subset (RM)
- [x] AMNH Novitates (RM)
- [x] Acta Palaeontologia Polonica (RM)
- [x] Science (RM)
- [x] Nature (RM)
- [x] PNAS (RM)
- [x] 2 Royal Society journals (RM)
- [x] 6 SciELO journals (RM)
- [x] 33 Springer journals (RM)
- [x] 130ish BioOne journals (RM)
- [x] 2 Cambridge University Press journals (RM)
- [x] 22 Wiley journals (RM) [here](https://github.com/rossmounce/NHM-specimens/blob/master/notes/newout/wileyBMNH-NHM.txt)
- [ ] 8 Elsevier journals (RM) [here](https://github.com/rossmounce/NHM-specimens/blob/master/notes/newout/ElsevierBMNH-NHM.txt)
- [ ] CSIRO journals (RM) [here](https://github.com/rossmounce/NHM-specimens/blob/master/notes/newout/CSIRO-NHMBMNHsearch.txt)
- [ ] 3 Oxford University Press journals (RM) [here](https://github.com/rossmounce/NHM-specimens/blob/master/notes/newout/oupBMNH-NHM.txt)
- [x] 12 Taylor and Francis journals (AR)
- [x] Zootaxa 2001 to 2005 (AR) [here](https://github.com/rossmounce/NHM-specimens/blob/master/notes/newout/zt2001to2005.txt)
- [x] Zootaxa 2006 (AR) [here](https://github.com/rossmounce/NHM-specimens/blob/master/notes/newout/zt2006.txt)
- [x] Zootaxa 2007 (AR) [here](https://github.com/rossmounce/NHM-specimens/blob/master/notes/newout/zt2007.txt)
- [x] Zootaxa 2008 (AR) [here](https://github.com/rossmounce/NHM-specimens/blob/master/notes/newout/zt2008.txt)
- [x] Zootaxa 2009 (AR) [here](https://github.com/rossmounce/NHM-specimens/blob/master/notes/newout/zt2009.txt)
- [ ] Zootaxa 2010 (AR) [here](https://github.com/rossmounce/NHM-specimens/blob/master/notes/newout/zt2010.txt)
- [ ] Zootaxa 2011 (AR) [here](https://github.com/rossmounce/NHM-specimens/blob/master/notes/newout/zt2011.txt)
- [ ] Zootaxa 2012 (RM) [here](https://github.com/rossmounce/NHM-specimens/blob/master/notes/newout/zt2012.txt)
- [ ] Zootaxa 2013 (RM) [here](https://github.com/rossmounce/NHM-specimens/blob/master/notes/newout/zt2013.txt)
- [ ] Zootaxa 2014 (RM) [here](https://github.com/rossmounce/NHM-specimens/blob/master/notes/newout/zt2014.txt)
- [ ] Zootaxa 2015 (RM) [here](https://github.com/rossmounce/NHM-specimens/blob/master/notes/newout/zt2015.txt)

**Comment by rossmounce** [comment]
@AimeRankin If we clean-up these files at a rate of 1 per week from today, it'll take ~2months. The Zootaxa files are typically 4000 to 6000 lines each. Does this sound like an achievable time-scale? If you can go faster, let me know. TandF is your biggest chunk tbh, the others are smaller pieces :sunglasses:

**Comment by AimeRankin** [comment]
@rossmounce That sounds like a good timetable to me!

**Comment by rossmounce** [comment]
:+1: :smiley:

**Comment by rossmounce** [comment]
@AimeRankin make sure you do a _git pull_ before you start your next work session. I've had a quick look at the tandf file & I've snipped out a couple of lines at around line 6040.

I don't have anything planned for this week's meeting. Can cancel it if you want, or use it to discuss something specific?

**Comment by AimeRankin** [comment]
@rossmounce I will do, I'm going to try and finish TandF over the next few days so I can start on Zootaxa before the weekend. I don't think there was anything specific I was going to discuss. I've noticed though that a few codes contain special characters that feature in the original papers and so don't appear to be errors. In rows 2791-2799 for example, some codes contain '$' which is interesting.

**Comment by rossmounce** [comment]
@AimeRankin cool! thanks for the notification about that, I'll have a look...
When you go-on to the Zootaxa files, start from 2001. I will make sure I have them a little bit more tidied-up for you by Friday. They are still very raw atm...
